apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: spiffe-csi-webhook
webhooks:
- name: "spire-spiffe-csi-webhook.spire-system.svc"
  clientConfig:
    caBundle: ${CA_BUNDLE}
    service:
      namespace: spire-system
      name: spire-spiffe-csi-webhook
      port: 8443
      path: "/mutate"
  rules:
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["deployments"]
    scope: "*"
  failurePolicy: Fail
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
